language: node_js
node_js:
  - "stable"
services:
  - postgresql
notifications:
  email: false
rvm:
  - 2.2.0
before_script:
  - psql -c 'create database aheaventest' -U postgres
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: npm run coverage
